config/routes.rb
Rails.application.routes.draw do
  resources :resenyas
  resources :histories
  get 'list_items/create'
  get 'list_items/destroy'
  get 'lcart', to: 'lcart#show'
  resources :claims
  get 'order_items/create'
  get 'order_items/update'
  get 'order_items/destroy'
  delete '/order_items/deleteAll', to:'order_items#destroy_all'
  get 'cart', to: 'cart#show'
  get 'ofertas', to: 'ofertas#show'
  get 'top_ventas', to: 'top_ventas#show'
  get '/moon', to: 'application#moon', as: 'moon'
  get '/sun', to: 'application#sun', as: 'sun'
  resources :brands
  resources :categories
  resources :products
  resources :order_items
  resources :list_items
  devise_for :accounts
  resources :accounts
  root to: 'public#main'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :claims
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/claim.rb
class Claim < ApplicationRecord
  belongs_to :account
end

app/models/history.rb
class History < ApplicationRecord
    has_one :order_item, class_name: "buyedItems", foreign_key: "buyed_items_id"
end

app/models/list.rb
class List < ApplicationRecord
    has_many :list_items
end

app/models/list_item.rb
class ListItem < ApplicationRecord
  belongs_to :product
  belongs_to :list
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items,:dependent => :destroy
  before_save :set_subtotal

  def subtotal
    order_items.collect { |order_item| order_item.valid? ? order_item.unit_price * order_item.quantity : 0 }.sum
  end
  

  private

  def set_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  before_save :set_unit_price
  before_save :set_total

  def unit_price
    # If there is a record
    if persisted?
      if product.onsale == true
        product.priceOnsale
      else
        self[:unit_price]
      end
      else
        product.price
      end
    end

  def total
    unit_price * quantity
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total
    self[:total] = total * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image
    belongs_to :category
    belongs_to :brand
end

app/models/resenya.rb
class Resenya < ApplicationRecord
  belongs_to :product
  belongs_to :account
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/lcart_helper.rb
module LcartHelper
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/helpers/ofertas_helper.rb
module OfertasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/resenyas_helper.rb
module ResenyasHelper
end

app/views/brands/_form.html.erb
<%= form_with(model: brand) do |form| %>
  <% if brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
        <% brand.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, "Nombre" %><br>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit "Guardar", class: "btn btn-dark text-white" %>
    <%= link_to 'Cancelar', brands_path, class: "btn btn-warning text-white" %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<section class="offset-md-2 col-md-8 col-xs-12 custom-form">
  <div class="d-flex justify-content-center mt-5 content">
    <div class="col-md-10 col-xs-12 py-4">
      <div class="row">
        <div class="col-12 text-center">
          <h1 class="mb-2">Editar marca</h1>
          <hr class="teal accent-3 mb-4 mt-0 mx-auto border-dark" style="width: 200px;">

          <%= render 'form', brand: @brand %>

          <%= link_to 'Ver', @brand, class: "btn btn-info text-white" %>

        </div>
      </div>
    </div>
  </div>
</section>

app/views/brands/index.html.erb
<section class="offset-md-1 col-md-10 col-xs-12">
  <div class="my-3 content p-5">
    <div class="w-100 text-center">
      <h1>Marcas</h1>
      <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto border-dark" style="width: 200px;">
    </div>

    <table class="table">
      <thead class="thead-dark">
      <tr>
        <th class="text-center">Nombre</th>
        <th colspan="3" class="text-center">Acciones</th>
      </tr>
      </thead>

      <tbody>
      <% @brands.each do |brand| %>
        <tr class="text-center">
          <td><%= brand.name %></td>
          <td>
            <%= link_to 'Ver', brand, class:"btn btn-info text-white" %>
            <%= link_to 'Editar', edit_brand_path(brand), class:"btn btn-success text-white" %>
            <%= link_to 'Eliminar', brand, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger text-white" %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div class="text-center">
      <%= link_to 'Nueva Marca', new_brand_path,class:"btn btn-dark text-white" %>
    </div>
  </div>
</section>

app/views/brands/new.html.erb
<section class="offset-md-2 col-md-8 col-xs-12 custom-form">
  <div class="d-flex justify-content-center mt-5 content">
    <div class="col-md-10 col-xs-12 py-4">
      <div class="row">
        <div class="col-12 text-center">
          <h1 class="mb-2">Nueva Marca</h1>
          <hr class="teal accent-3 mb-4 mt-0 mx-auto border-dark" style="width: 200px;">

          <%= render 'form', brand: @brand %>

        </div>
      </div>
    </div>
  </div>
</section>

app/views/brands/show.html.erb
<section class="offset-md-2 col-md-8 col-xs-12">
  <div class="d-flex justify-content-center mt-5 content">
    <div class="col-12 py-4">
      <div class="w-100 text-center mb-3">
        <h1>Información de la marca</h1>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto border-dark" style="width: 200px;">
      </div>

      <div class="row">
        <div class="col-md-12 text-center">

          <p>
            <strong>Nombre:</strong>
            <%= @brand.name %>
          </p>

          <%= link_to 'Editar', edit_brand_path(@brand), class: "btn btn-success text-white" %>
          <%= link_to 'Volver', brands_path, class: "btn btn-info text-white" %>

        </div>
      </div>
    </div>
  </div>
</section>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, "Nombre" %><br>
    <%= form.text_field :name %>
  </div>

  <div class="form-group">
    <%= form.label :details, "Detalles" %><br>
    <%= form.text_area :details %>
  </div>

  <div class="actions">
    <%= form.submit "Guardar", class: "btn btn-dark text-white" %>
    <%= link_to 'Cancelar', categories_path, class: "btn btn-warning text-white" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<section class="offset-md-2 col-md-8 col-xs-12 custom-form">
  <div class="d-flex justify-content-center mt-5 content">
    <div class="col-md-10 col-xs-12 py-4">
      <div class="row">
        <div class="col-12 text-center">
          <h1 class="mb-2">Editar categoría</h1>
          <hr class="teal accent-3 mb-4 mt-0 mx-auto border-dark" style="width: 200px;">

          <%= render 'form', category: @category %>

          <%= link_to 'Ver', @category, class: "btn btn-info text-white" %>

        </div>
      </div>
    </div>
  </div>
</section>

app/views/categories/index.html.erb
<section class="offset-md-1 col-md-10 col-xs-12">
  <div class="my-3 content p-5">

    <div class="w-100 text-center">
      <h1>Categorías</h1>
      <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto border-dark" style="width: 200px;">
    </div>

    <table class="table">
      <thead class="thead-dark">
      <tr>
        <th class="text-center">Nombre</th>
        <th class="text-center">Detalles</th>
        <th colspan="3" class="text-center">Acciones</th>
      </tr>
      </thead>

      <tbody>
      <% @categories.each do |category| %>
        <tr class="text-center">
          <td class="align-middle"><%= category.name %></td>
          <td class="align-middle"><%= category.details %></td>
          <td class="align-middle">
            <%= link_to 'Ver', category, class: "btn btn-info text-white" %>
            <%= link_to 'Editar', edit_category_path(category), class: "btn btn-success text-white" %>
            <%= link_to 'Eliminar', category, class: "btn btn-danger text-white", method: :delete, data: { confirm: '¿Estas seguro?' } %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <div class="text-center">
      <%= link_to 'Nueva Categoría', new_category_path,class:"btn btn-dark text-white" %>
    </div>

  </div>
</section>

app/views/categories/new.html.erb
<section class="offset-md-2 col-md-8 col-xs-12 custom-form">
  <div class="d-flex justify-content-center mt-5 content">
    <div class="col-md-10 col-xs-12 py-4">
      <div class="row">
        <div class="col-12 text-center">
          <h1 class="mb-2">Nueva Categoría</h1>
          <hr class="teal accent-3 mb-4 mt-0 mx-auto border-dark" style="width: 200px;">

          <%= render 'form', category: @category %>

        </div>
      </div>
    </div>
  </div>
</section>

app/views/categories/show.html.erb
<section class="offset-md-2 col-md-8 col-xs-12">
  <div class="d-flex justify-content-center mt-5 content">
    <div class="col-12 py-4">
      <div class="w-100 text-center mb-3">
        <h1>Información de la categoría</h1>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto border-dark" style="width: 200px;">
      </div>

      <div class="row">
        <div class="col-md-12 text-center">

          <p>
            <strong>Nombre:</strong>
            <%= @category.name %>
          </p>

          <p>
            <strong>Detalles:</strong>
            <%= @category.details %>
          </p>

          <%= link_to 'Editar', edit_category_path(@category), class: "btn btn-success text-white" %>
          <%= link_to 'Volver', categories_path, class: "btn btn-info text-white" %>

        </div>
      </div>
    </div>
  </div>
</section>

app/views/histories/index.html.erb
<section class="offset-md-1 col-md-10 col-xs-12">
  <div class="my-5 content py-3 ">
    <div class="w-100 text-center">
      <h1>Historial de compra</h1>
      <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto border-dark" style="width: 200px;">
    </div>
    <div class="table-responsive">
      <table class="table table-striped">

        <thead>
        <tr>
          <th class="text-center">Nºtarjeta</th>
          <th class="text-center">Domicilio</th>
          <th class="text-center">Reclamaciones</th>
          <th class="text-center" colspan="2">Acciones</th>
        </tr>
        </thead>
        <tbody>
        <% @histories.each do |history| %>
          <tr>

            <td class="text-center align-middle">
              <%= history.tarjeta %>
            </td>

            <td class="text-center align-middle">
              <% if history.domicilio %>
                <p>Sí</p>
              <% else %>
                <p>No</p>
              <% end %>
            </td>

            <td class="text-center align-middle">
              <%= link_to 'Enviar', new_claim_path, class: "btn btn-success text-white" %>
            </td>

            <td class="text-center align-middle">
              <%= link_to 'Ver Compra', history, class: "btn btn-info text-white" %>
              <%= link_to "Ver reclamaciones", claims_path, class:"btn btn-warning text-white"  %>
            </td>

          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="text-center align-middle">
      <%= link_to "Volver al catálogo", order_items_deleteAll_path, method: :delete, class: "btn btn-dark mt-2 text-white" %>
    </div>
  </div>
</section>

app/views/histories/show.html.erb
<section class="offset-md-1 col-md-10 col-xs-12">
  <div class="my-5 content py-3 ">
    <div class="w-100 text-center">
      <h1>Detalles de compra</h1>
      <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto border-dark" style="width: 200px;">
    </div>
    <div class="table-responsive">
      <table class="table table-striped">

        <thead>
        <tr>
          <th class="text-center">Nºtarjeta</th>
          <th class="text-center">Artículo</th>
          <th class="text-center">Domicilio</th>
          <th class="text-center">Precio</th>
        </tr>
        </thead>
        <tbody>
        <% @buyedItems.each do |item| %>
          <tr>
            <td class="text-center align-middle">
              <%= @history.tarjeta %>
            </td>
            <td class="text-center align-middle">
              <%= image_tag(item.product.image, class:"img-fluid rounded ml-2", style: "width: 100px") %>
              <%= item.product.name%>
            </td>
            <td class="text-center align-middle">
              <% if @history.domicilio %>
                <p>Sí</p>
              <% else %>
                <p>No</p>
              <% end %>
            </td>
            <td class="text-center align-middle">
              <%= number_to_currency item.total, :locale => :en %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <%if @history.domicilio === true %>
      <div class="text-center align-middle">
        <%days = Time.now.strftime("%d %b %y").to_i - @history.created_at.strftime("%d %b %y").to_i%>
        <%dia_llegada = @history.created_at + 5.days %>
        <h3>Seguimiento</h3>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto border-dark" style="width: 200px;">
        <div class="table-responsive">
        <%if days <5 %>
            <h4> El pedido llegará el <%=dia_llegada.strftime("%d %b %y")%> , quedan <%=5 -days%> días.</h4>
        <%else%>
          <h4>El pedido llegó el <%=dia_llegada.strftime("%d %b %y")%>.</h4>
        <%end%>
        </div>
      </div>
      <%end%>
    <div class="text-center align-middle">
      <%= link_to 'Volver', histories_path, class: "btn btn-success mt-2 text-white" %>
    </div>
  </div>
</section>