config/routes.rb
Rails.application.routes.draw do
  resources :resenyas
  resources :histories
  get 'list_items/create'
  get 'list_items/destroy'
  get 'lcart', to: 'lcart#show'
  resources :claims
  get 'order_items/create'
  get 'order_items/update'
  get 'order_items/destroy'
  delete '/order_items/deleteAll', to:'order_items#destroy_all'
  get 'cart', to: 'cart#show'
  get 'ofertas', to: 'ofertas#show'
  get 'top_ventas', to: 'top_ventas#show'
  get '/moon', to: 'application#moon', as: 'moon'
  get '/sun', to: 'application#sun', as: 'sun'
  resources :brands
  resources :categories
  resources :products
  resources :order_items
  resources :list_items
  devise_for :accounts
  resources :accounts
  root to: 'public#main'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :claims
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/claim.rb
class Claim < ApplicationRecord
  belongs_to :account
end

app/models/history.rb
class History < ApplicationRecord
    has_one :order_item, class_name: "buyedItems", foreign_key: "buyed_items_id"
end

app/models/list.rb
class List < ApplicationRecord
    has_many :list_items
end

app/models/list_item.rb
class ListItem < ApplicationRecord
  belongs_to :product
  belongs_to :list
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items,:dependent => :destroy
  before_save :set_subtotal

  def subtotal
    order_items.collect { |order_item| order_item.valid? ? order_item.unit_price * order_item.quantity : 0 }.sum
  end
  

  private

  def set_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  before_save :set_unit_price
  before_save :set_total

  def unit_price
    # If there is a record
    if persisted?
      if product.onsale == true
        product.priceOnsale
      else
        self[:unit_price]
      end
      else
        product.price
      end
    end

  def total
    unit_price * quantity
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total
    self[:total] = total * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image
    belongs_to :category
    belongs_to :brand
end

app/models/resenya.rb
class Resenya < ApplicationRecord
  belongs_to :product
  belongs_to :account
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  def search
    @search = params[:search]
    @products = Product.where("name lIKE ?","%#{@search}%")
  end

  # GET /products/1 or /products/1.json
  def show
    @order_item = current_order.order_items.new
    @list_item = current_list.list_items.new
    @product = Product.includes(:category, :brand).find(params[:id])
    @resenya = Resenya.all
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price, :description, :marca, :onsale, :image, :category_id, :brand_id, :priceOnsale)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/lcart_helper.rb
module LcartHelper
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/helpers/ofertas_helper.rb
module OfertasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/resenyas_helper.rb
module ResenyasHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <!-- Bloque izquierda -->
    <div class="col-md-6 col-xs-12">

      <!-- Box name -->
      <div class="form-group">
        <%= form.label :name, "Nombre" %><br />
        <%= form.text_field :name %>
      </div>
      <!-- /Box name -->

      <!-- Box price -->
      <div class="form-group">
        <%= form.label :price, "Precio" %><br />
        <%= form.text_field :price %>
      </div>
      <!-- /Box price -->

      <!-- Box category -->
      <div class="form-group">
        <label for="category_id">Categoría</label>
        <select name="product[category_id]" class="form-control col-md-8 offset-2">
          <option value="null">Seleccione categoría</option>
          <% Category.all.each do |c| %>
            <option value="<%= c.id %>" <%= @product.category_id == c.id ? "selected" : ""%>><%= c.name%></option>
          <% end %>
        </select>
      </div>
      <!-- /Box category -->

      <!-- Box brand -->
      <div class="form-group">
        <label for="brand_id">Marca</label>
        <select name="product[brand_id]" class="form-control col-md-8 offset-2">
          <option value="null">Seleccione marca</option>
          <% Brand.all.each do |b| %>
            <option value="<%= b.id %>" <%= @product.brand_id == b.id ? "selected" : ""%>><%= b.name%></option>
          <% end %>
        </select>
      </div>
      <!-- /Box brand -->

    </div>
    <!-- /Bloque izquierda -->

    <!-- Bloque derecha -->
    <div class="col-md-6 col-xs-12">

      <!-- Box description -->
      <div class="form-group">
        <%= form.label :description, "Descripción" %>
        <%= form.text_area :description %>
      </div>
      <!-- /Box description -->

      <!-- Box onsale -->
      <div class="form-group">
        <%= form.label :onsale, "Oferta" %>
        <%= form.check_box :onsale %>
      </div>
      <!-- /Box onsale -->

      <!-- Box priceOnsale -->
      <div class="form-group">
        <%= form.label :priceOnsale, "Precio de oferta" %>
        <%= form.text_field :priceOnsale %>
      </div>
      <!-- /Box priceOnsale -->

      <!-- Box image -->
      <div class="form-group">
        <%= form.label :image, "Imagen" %>
        <%= form.file_field :image %>
      </div>
      <!-- /Box image -->

    </div>
    <!-- /Bloque derecha -->
  </div>

  <div class="actions">
    <%= form.submit "Guardar", class: "btn btn-dark text-white" %>
    <%= link_to 'Cancelar', products_path, class:"btn btn-warning text-white" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<section class="offset-md-2 col-md-8 col-xs-12 custom-form">
  <div class="d-flex justify-content-center mt-5 content">
    <div class="col-md-10 col-xs-12 py-4">
      <div class="row">
        <div class="col-12 text-center">
          <h1 class="mb-2">Editar Producto</h1>
          <hr class="teal accent-3 mb-4 mt-0 mx-auto border-dark" style="width: 200px;">
          <%= render 'form', product: @product %>
          <%= link_to 'Ver', @product, class: "btn btn-info text-white"  %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/products/index.html.erb
<section class="offset-md-1 col-md-10 col-xs-12">
  <div class="my-3 content p-5">
    <div class="w-100 text-center">
      <h1>Productos</h1>
      <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto border-dark" style="width: 200px;">
    </div>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th class="text-center">Nombre</th>
        <th class="text-center">Precio</th>
        <th class="text-center">Descripcion</th>
        <th class="text-center">Marca</th>
        <th class="text-center">Categoría</th>
        <th colspan="3" class="text-center">Acciones</th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
        <tr class="text-center">
          <td class="align-middle"><%= product.name %></td>
          <td class="align-middle"><%= product.price %></td>
          <td class="align-middle"><%= product.description %></td>
          <td class="align-middle"><%= product.brand.name %></td>
          <td class="align-middle"><%= product.category.name %></td>
          <td class="align-middle">
            <%= link_to 'Ver', product, class:"btn btn-info text-white" %>
            <%= link_to 'Editar', edit_product_path(product),class:"btn btn-success text-white" %>
            <%= link_to 'Eliminar', product, method: :delete, data: { confirm: '¿Estas seguro?' },class:"btn btn-danger text-white" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
    <div class="text-center">
      <%= link_to 'Nuevo producto', new_product_path , class:"btn btn-dark text-white"%>
    </div>
  </div>
</section>

app/views/products/new.html.erb
<section class="offset-md-2 col-md-8 col-xs-12 custom-form">
  <div class="d-flex justify-content-center mt-5 content">
    <div class="col-md-10 col-xs-12 py-4">
      <div class="row">
        <div class="col-12 text-center">
          <h1 class="mb-2">Nuevo Producto</h1>
          <hr class="teal accent-3 mb-4 mt-0 mx-auto border-dark" style="width: 200px;">
          <%= render 'form', product: @product %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/products/show.html.erb
<section class="offset-md-1 col-md-10 col-xs-12">
  <div class="d-flex justify-content-center mt-5 content">
    <div class="col-sm-12 py-4">
      <div class="row">
        <div class="col-md-3 mb-3 text-center">
          <%= image_tag(@product.image, class:"img-fluid rounded") %>
        </div>
        <div class="col-md-5">
          <h3><%= @product.name %></h3>
          <h5><%= @product.description %></h5>
        </div>
        <div class="col-md-4 mt-5">
          <table class="table">
            <tbody>
            <tr>
              <th>
                Marca
              </th>
              <td>
                <%= @product.brand.name %>
              </td>
            </tr>
            <tr>
              <th>
                Categoría
              </th>
              <td>
                <%= @product.category.name %>
              </td>
            </tr>
            </tbody>
          </table>
        </div>
        <div class="col-md-3 text-center mt-3">
          <div class="alert alert-dark p-2 my-auto">
            <% if @product.onsale == true %>
             <h5> <%= number_to_currency @product.priceOnsale, :locale => :en %></h5>
            <% else %>
              <h5> <%= number_to_currency @product.price, :locale => :en %></h5>
            <% end %>
          </div>

          <%if account_signed_in? && !current_account.isAdmin %>
            <div class="mt-2">
              <%= form_for(@list_item, remote: true) do |l| %>
                <%= l.hidden_field :product_id, value: @product.id %>
                <%= l.submit "Añadir a favoritos", class: "btn btn-warning text-dark" %>
                <%= link_to 'Añadir Reseña', new_resenya_path, class:"btn btn-success text-white mt-3" %>
              <% end %>
            </div>
          <% end %>

        </div>

        <div class="col-md-4 text-center mt-3">
          <%= form_for(@order_item, remote: true) do |f| %>
            <%= f.hidden_field :product_id, value: @product.id %>
            <%= f.number_field :quantity, value: 1, min: 1%>
            <%= f.submit "Añadir al carrito", class: "btn btn-dark mt-2" %>
          <% end %>
        </div>

        <div class="col-md-4 text-center mt-3">
          <%= link_to 'Volver', root_path, class:"btn btn-info text-white" %>
        </div>
      </div>
    </div>
  </div>

  <%if account_signed_in? && !current_account.isAdmin %>
    <div class="my-5 content py-3 ">
      <div class="w-100 text-center">
        <h1>Reseñas</h1>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto border-dark" style="width: 200px;">
      </div>

      <div class="table-responsive">
        <table class="table table-striped">

          <thead>
          <tr>
            <th class="text-center">Usuario</th>
            <th class="text-center">Valoración</th>
            <th class="text-center">Comentario</th>
          </tr>
          </thead>

          <tbody>
          <% if @product.id == 9 %>
            <% @resenya.each do |r| %>
                <tr>
                  <td class="text-center">
                    <%= r.account.nombre %>
                    <%= r.account.apellidos %>
                  </td>
                  <td class="text-center">
                    <%= r.valoracion %>
                  </td>
                  <td class="text-center">
                    <%= r.descripcion %>
                  </td>
                </tr>
            <% end %>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>
</section>