config/routes.rb
Rails.application.routes.draw do
  resources :resenyas
  resources :histories
  get 'list_items/create'
  get 'list_items/destroy'
  get 'lcart', to: 'lcart#show'
  resources :claims
  get 'order_items/create'
  get 'order_items/update'
  get 'order_items/destroy'
  delete '/order_items/deleteAll', to:'order_items#destroy_all'
  get 'cart', to: 'cart#show'
  get 'ofertas', to: 'ofertas#show'
  get 'top_ventas', to: 'top_ventas#show'
  get '/moon', to: 'application#moon', as: 'moon'
  get '/sun', to: 'application#sun', as: 'sun'
  resources :brands
  resources :categories
  resources :products
  resources :order_items
  resources :list_items
  devise_for :accounts
  resources :accounts
  root to: 'public#main'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :claims
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/claim.rb
class Claim < ApplicationRecord
  belongs_to :account
end

app/models/history.rb
class History < ApplicationRecord
    has_one :order_item, class_name: "buyedItems", foreign_key: "buyed_items_id"
end

app/models/list.rb
class List < ApplicationRecord
    has_many :list_items
end

app/models/list_item.rb
class ListItem < ApplicationRecord
  belongs_to :product
  belongs_to :list
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items,:dependent => :destroy
  before_save :set_subtotal

  def subtotal
    order_items.collect { |order_item| order_item.valid? ? order_item.unit_price * order_item.quantity : 0 }.sum
  end
  

  private

  def set_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  before_save :set_unit_price
  before_save :set_total

  def unit_price
    # If there is a record
    if persisted?
      if product.onsale == true
        product.priceOnsale
      else
        self[:unit_price]
      end
      else
        product.price
      end
    end

  def total
    unit_price * quantity
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total
    self[:total] = total * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image
    belongs_to :category
    belongs_to :brand
end

app/models/resenya.rb
class Resenya < ApplicationRecord
  belongs_to :product
  belongs_to :account
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/lcart_helper.rb
module LcartHelper
end

app/helpers/ofertas_helper.rb
module OfertasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/resenyas_helper.rb
module ResenyasHelper
end

app/views/layouts/_nav.html.erb
<header>
<link id="pagestyle" rel="stylesheet" href="light.css">
  <nav class="navbar navbar-expand bg-dark navbar-dark mb-4">
    <div class="container-fluid">
      <a href="http://127.0.0.1:3000/">
        <%= image_tag "logo_500x500_white.png", class:"d-inline-block align-top", height:'50' %>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        
        <ul class="navbar-nav mr-auto mb-2 mb-md-0">

          <li class="nav-item">
            <%= link_to "Ofertas", ofertas_path, class:"nav-link"  %>
          </li>

          <li class="nav-item">
            <%= link_to "Top Ventas", top_ventas_path, class:"nav-link"  %>
          </li>

          <% if account_signed_in? && !current_account.isAdmin %>

            <li class="nav-item">
              <%= link_to "Favoritos", lcart_path, class:"nav-link"  %>
            </li>

            <li class="nav-item">
              <%= link_to "Carrito", cart_path, class:"nav-link"  %>
            </li>

          <%elsif account_signed_in? && current_account.isAdmin %>
            <li class="nav-item">
              <%= link_to "Productos", products_path, class:"nav-link"  %>
            </li>

            <li class="nav-item">
              <%= link_to "Categorías", categories_path, class:"nav-link"  %>
            </li>

            <li class="nav-item">
              <%= link_to "Marcas", brands_path, class:"nav-link"  %>
            </li>

            <li class="nav-item">
              <%= link_to "Usuarios", accounts_path, class:"nav-link"  %>
            </li>

          <% end %>

        </ul>

        <% if !account_signed_in? || !current_account.isAdmin %>
          <form class="form-inline ml-2">
            <input class="form-control me-2 col-md-3" type="search" placeholder="Buscar" aria-label="Search" name="search" <%= @search%>>
            <button class="ml-2 btn btn-outline-success" type="submit">Buscar</button>
            <select class="ml-2 form-select form-select-sm text-white border-success bg-secondary" name="selectcategoria" id="selectcategoria"<%= @selectcategoria%>>
              <option value="0">Categoría</option>
              <option value="1">Ordenadores</option>
              <option value="2">Monitores</option>
              <option value="3">Teclados</option>
              <option value="4">Ratones</option>
              <option value="5">Portátiles</option>
            </select>
            <select class="ml-2 form-select form-select-sm text-white border-success bg-secondary" name="selectMarca" id="selectMarca"<%= @selectmarca%>>
              <option value="0">Marcas</option>
              <option value="1">Apple</option>
              <option value="2">Microsoft</option>
              <option value="3">Samsung</option>
              <option value="4">LG</option>
              <option value="5">Razer</option>
            </select>
            <input type="checkbox" class=" ml-2 btn-check active" id="btn-check-outlined" name="recientes" autocomplete="off" <%= @checkrecientes%>>
            <label class="ml-1 btn btn-outline-secondary border-success active btn-sm" for="btn-check-outlined">Más recientes</label>
          </form>
        <% end %>

        <ul class="navbar-nav mb-2 mb-md-0">
          <%if !account_signed_in? %>
            <li class="nav-item">
              <%= link_to "Crear cuenta", new_account_registration_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Iniciar sesión", new_account_session_path, class:"nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Mi perfil", edit_account_registration_path, class:"nav-link"  %>
            </li>
            <li class="nav-item">
              <%= link_to "Cerrar sesión", destroy_account_session_path, method: :delete, class:"nav-link"  %>
            </li>
          <%end%>

          <% if cookies[:moon] %>
            <%= link_to 'Modo oscuro', sun_path, method: :get , class:"nav-link"%>
          <% else %>
            <%= link_to 'Modo claro', moon_path, method: :get , class:"nav-link"%>
          <% end %>

        </ul>

      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Infotronics</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag 'logo_32x32.png' %>

    <% if cookies[:moon] %>
    <%= stylesheet_link_tag 'application_dark', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% else %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% end %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    
    
  
  </head>

  <body id="bodyjeje" >
    <%= render 'layouts/nav'%>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>